## Name: Nagpurkar Manthan Tulsiram
## Enrollment No: 190130107071
## Subject: PDS(3150713)
## Sem: 5
## Class: CE-A

## Practical-18

In [26]:
import numpy as np
arr = np.array([1,4,0,2,6,8])

In [29]:
arr.any()

True

In [28]:
arr.all() # 0 occured in arr 

False

In [42]:
print("arr = ", np.isnan(arr))
a = np.array([np.nan, np.nan, 1, 5, 6])
print("a = ", np.isnan(a))

arr =  [False False False False False False]
a =  [ True  True False False False]


In [43]:
a = np.array([1, 5, 1000, 24, 525, np.inf])
print("a = ", np.isinf(a))

a =  [False False False False False  True]


In [44]:
np.isfinite(a)

array([ True,  True,  True,  True,  True, False])

In [51]:
ar = np.zeros((2,2))
ar

array([[0., 0.],
       [0., 0.]])

In [59]:
ar = np.array([1+2j, 3+10j, 24, 5]) # mixture of complex and real values 
np.isreal(ar)

array([False, False,  True,  True])

In [60]:
np.iscomplex(ar)

array([ True,  True, False, False])

In [63]:
np.isscalar([24])

False

In [64]:
np.isscalar(24)

True

In [74]:
x = np.array([1,3,7])
y = np.array([2, 5,6])
np.less(x, y)

array([ True,  True, False])

In [75]:
np.less(y, x)

array([False, False,  True])

In [76]:
np.greater(x, y)

array([False, False,  True])

In [77]:
np.greater(y, x)

array([ True,  True, False])

In [79]:
x = np.array([1, 4, 10])
y = np.array([2, 4, 8])
np.less_equal(x, y)

array([ True,  True, False])

In [80]:
np.greater_equal(x, y)

array([False,  True,  True])

## Practical-19

In [81]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [86]:
ar = np.array([[1, 4, 5],
              [4, 5, 52]])
ar.shape

(2, 3)

In [91]:
ar.reshape(3, 2)

array([[ 1,  4],
       [ 5,  4],
       [ 5, 52]])

In [93]:
np.linspace(1, 40, 10) # ten values with same difference betweem 1 to 40

array([ 1.        ,  5.33333333,  9.66666667, 14.        , 18.33333333,
       22.66666667, 27.        , 31.33333333, 35.66666667, 40.        ])

In [101]:
np.random.randint(0,500)

292

In [105]:
x = np.array([1, 5, 10])
y = np.array([4, 5, 12])
z = x*y
print(z)
x.dot(y) # Sum of array z

[  4  25 120]


149